apiVersion: v1
kind: Service
metadata:
    name: "accapp-e1e8"
    labels:
        app: "accapp-e1e8"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "accapp-e1e8"